export const GENRE_IMAGES: Record<string, string> = {
  history: "/src/assets/genres/history.png",
  horror: "/src/assets/genres/horror.png",
  scifi: "/src/assets/genres/scifi.png",
  "stand-up": "/src/assets/genres/stand-up.png",
  fantasy: "/src/assets/genres/fantasy.png",
  drama: "/src/assets/genres/drama.png",
  mystery: "/src/assets/genres/mystery.png",
  family: "/src/assets/genres/family.png",
  comedy: "/src/assets/genres/comedy.png",
  romance: "/src/assets/genres/romance.png",
  music: "/src/assets/genres/music.png",
  crime: "/src/assets/genres/crime.png",
  "tv-movie": "/src/assets/genres/tv-movie.png",
  documentary: "/src/assets/genres/documentary.png",
  action: "/src/assets/genres/action.png",
  thriller: "/src/assets/genres/thriller.png",
  western: "/src/assets/genres/western.png",
  animation: "/src/assets/genres/animation.png",
  war: "/src/assets/genres/war.png",
  adventure: "/src/assets/genres/adventure.png",
};

export const GENRE_TRANSLATIONS: Record<string, string> = {
  history: "Исторический",
  horror: "Ужасы",
  scifi: "Фантастика",
  "stand-up": "Стендап",
  fantasy: "Фэнтези",
  drama: "Драма",
  mystery: "Детектив",
  family: "Семейный",
  comedy: "Комедия",
  romance: "Мелодрама",
  music: "Музыкальный",
  crime: "Криминал",
  "tv-movie": "ТВ-фильм",
  documentary: "Документальный",
  action: "Боевик",
  thriller: "Триллер",
  western: "Вестерн",
  animation: "Мультфильм",
  war: "Военный",
  adventure: "Приключения",
};
